---

- hosts: proxy_servers
  tags:
    - proxy
  tasks:
    - name: start Proxy by supervise
      shell: cd {{ deploy_dir }}/scripts && ./start_{{ item }}.sh
      when: process_supervision == 'supervise'
      with_items:
        - proxy

    - name: start Proxy by systemd
      systemd: name=proxy-{{ proxy_port }}.service state=started enabled=no
      become: true
      when: process_supervision == 'systemd'

    - name: wait for Proxy up
      wait_for_pid: |
        pid_file={{ deploy_dir }}/status/proxy.pid timeout=300
        thread_name_regex='tikv-proxy' state=present
      when: deployment_method == 'binary'

    - name: wait for Proxy up
      wait_for: host={{ ansible_host }} port={{ proxy_port }} state=present
      when: deployment_method == 'docker'

    - command: cat {{ deploy_dir }}/status/proxy.pid
      register: new_proxy_pid
      ignore_errors: yes
      changed_when: false

    - name: display new proxy pid
      debug:
        msg: "proxy binary or docker pid: {{ new_proxy_pid.stdout }}"


