---

- name: create config file
  template: src={{ playbook_dir }}/conf/proxy.toml dest={{ deploy_dir }}/conf/proxy.toml mode=0644 backup=yes

- include_tasks: "{{ deployment_method }}_deployment.yml"

